#default        
multipart:
    maxFileSize: 5120KB
    maxRequestSize: 10240KB
    
uploadpath:
        announcements: C:\upload\jeiglobal\hk\announcements
        
server:
    port: 8081
    
serverurl:
     hongkong: http://localhost:8080
     globalbms: http://localhost:8081
         
cookieShare:
     domain: localhost
     
filePath:
     img: /public/img
     js: /public/js
     css: /public/css
     
page:
    blockSize: 10  # 한 블록에 출력될 페이지 개수
    size: 10      # 한 페이지에 출력될 레코드 개수 
---
spring.profiles: develop

#develop        
multipart:
    maxFileSize: 5120KB
    maxRequestSize: 10240KB
    
uploadpath:
        announcements: /home/devhk/upload/announcements
        
spring:
    resources:
        cache-period:31556926
        
serverurl:
     hongkong: http://devhk.jei-global.com
     globalbms: http://devbms.jei-global.com
     
cookieShare:
     domain: .jei-global.com

page:
    blockSize: 10  # 한 블록에 출력될 페이지 개수
    size: 10      # 한 페이지에 출력될 레코드 개수 
---
spring.profiles: product

#product
multipart:
    maxFileSize: 5120KB
    maxRequestSize: 10240KB
    
uploadpath:
        announcements: /home/devhk/upload/announcements
        
spring:
    resources:
        cache-period:31556926
        
cookieShare:
     domain: .jei-global.com

page:
    blockSize: 10  # 한 블록에 출력될 페이지 개수
    size: 100      # 한 페이지에 출력될 레코드 개수 
